#!/usr/bin/env python3

# Quick script to replace the 10 developers with proper names and add more

developers_js = '''const allDevelopers = [
			{id: 'R001', name: 'Trading Titan', position: 'Senior React Developer', category: 'React', technologies: ['React','TypeScript','Redux','Next.js','Node.js'], experienceYears: 8, salaryUSD: 6200, englishLevel: 'Upper-Intermediate', industry: 'Fintech • E-commerce', rating: 4.9, techLevel: 142, availability: 'Available now', businessImpact: 'Built trading platform handling $50M+ daily volume • Led team of 7'},
			{id: 'R002', name: 'Load Killer', position: 'Frontend Tech Lead', category: 'React', technologies: ['React','TypeScript','Micro-frontends','Webpack','Docker'], experienceYears: 10, salaryUSD: 7000, englishLevel: 'Advanced', industry: 'Enterprise • SaaS', rating: 5.0, techLevel: 156, availability: '2 weeks notice', businessImpact: 'Architected system serving 2M+ users • Reduced load time by 65%'},
			{id: 'R003', name: 'Dating Destroyer', position: 'React Native Developer', category: 'React', technologies: ['React Native','TypeScript','Redux','Firebase','iOS'], experienceYears: 5, salaryUSD: 4200, englishLevel: 'Upper-Intermediate', industry: 'Social Media • Dating Apps', rating: 4.8, techLevel: 98, availability: 'Available now', businessImpact: 'Dating app with 500k+ downloads • 40% user retention rate'},
			{id: 'R004', name: 'Health Hero', position: 'Mid React Developer', category: 'React', technologies: ['React','JavaScript','Redux Toolkit','Material-UI','Jest'], experienceYears: 4, salaryUSD: 3100, englishLevel: 'Intermediate', industry: 'Healthcare • EduTech', rating: 4.7, techLevel: 76, availability: 'Available now', businessImpact: 'Patient portal used by 200+ hospitals • HIPAA compliant'},
			{id: 'R005', name: 'Corporate Crusher', position: 'Junior React Developer', category: 'React', technologies: ['React','JavaScript','HTML5','CSS3','Git'], experienceYears: 2, salaryUSD: 2200, englishLevel: 'Pre-Intermediate', industry: 'Startups • Corporate', rating: 4.6, techLevel: 52, availability: 'Available now', businessImpact: 'Corporate dashboard for HR processes • Clean, responsive design'},
			{id: 'R006', name: 'Banking Beast', position: 'Full Stack React Engineer', category: 'React', technologies: ['React','Next.js','Node.js','PostgreSQL','AWS'], experienceYears: 6, salaryUSD: 4800, englishLevel: 'Upper-Intermediate', industry: 'Banking • Insurance', rating: 4.9, techLevel: 118, availability: '1 month notice', businessImpact: 'Banking app with 300k+ active users • 99.8% uptime SLA'},
			{id: 'R007', name: 'Stream King', position: 'React Specialist', category: 'React', technologies: ['React','TypeScript','GraphQL','Apollo','Storybook'], experienceYears: 7, salaryUSD: 5400, englishLevel: 'Upper-Intermediate', industry: 'Media • Entertainment', rating: 4.9, techLevel: 125, availability: 'Available now', businessImpact: 'Streaming platform with 1M+ concurrent users • CDN optimization'},
			{id: 'R008', name: 'E-com Emperor', position: 'Frontend Developer', category: 'React', technologies: ['React','Vue.js','JavaScript','Sass','Webpack'], experienceYears: 3, salaryUSD: 2800, englishLevel: 'Intermediate', industry: 'E-commerce • Retail', rating: 4.7, techLevel: 67, availability: 'Available now', businessImpact: 'E-commerce platform with $5M+ annual GMV • Mobile conversion +45%'},
			{id: 'R009', name: 'Booking Boss', position: 'React Developer', category: 'React', technologies: ['React','TypeScript','Redux','REST APIs','Firebase'], experienceYears: 4, salaryUSD: 3600, englishLevel: 'Intermediate', industry: 'Travel • Hospitality', rating: 4.8, techLevel: 81, availability: 'Available now', businessImpact: 'Booking platform for 500+ hotels • Real-time availability system'},
			{id: 'R010', name: 'Speed Demon', position: 'Senior Frontend Developer', category: 'React', technologies: ['React','TypeScript','Next.js','TailwindCSS','Vercel'], experienceYears: 5, salaryUSD: 4500, englishLevel: 'Advanced', industry: 'SaaS • Productivity', rating: 4.8, techLevel: 102, availability: 'Available now', businessImpact: 'Dashboard with 50ms load time • 99.9% uptime for 100k+ users'},
			{id: 'P001', name: 'Payment Pro', position: 'Senior Python Developer', category: 'Python', technologies: ['Python','Django','FastAPI','PostgreSQL','Redis'], experienceYears: 9, salaryUSD: 6500, englishLevel: 'Upper-Intermediate', industry: 'Fintech • Banking', rating: 4.9, techLevel: 145, availability: '2 weeks notice', businessImpact: 'Payment processing system handling $1B+ annually • PCI DSS compliant'},
			{id: 'P002', name: 'ML Master', position: 'ML Python Engineer', category: 'Python', technologies: ['Python','TensorFlow','PyTorch','Pandas','AWS'], experienceYears: 6, salaryUSD: 5800, englishLevel: 'Upper-Intermediate', industry: 'AI/ML • Data Science', rating: 4.9, techLevel: 124, availability: 'Available now', businessImpact: 'Recommendation engine increasing sales by 35% • 500M+ predictions daily'},
			{id: 'P003', name: 'E-com Backend', position: 'Django Developer', category: 'Python', technologies: ['Python','Django','REST API','PostgreSQL','Celery'], experienceYears: 5, salaryUSD: 4200, englishLevel: 'Intermediate', industry: 'E-commerce • Retail', rating: 4.8, techLevel: 89, availability: 'Available now', businessImpact: 'E-commerce backend serving 100k+ orders monthly • API optimization'},
			{id: 'P004', name: 'Social Builder', position: 'Python Backend Engineer', category: 'Python', technologies: ['Python','Flask','SQLAlchemy','MongoDB','RabbitMQ'], experienceYears: 4, salaryUSD: 3800, englishLevel: 'Intermediate', industry: 'Social Media • Content', rating: 4.7, techLevel: 78, availability: 'Available now', businessImpact: 'Social platform with 200k+ active users • Real-time messaging system'},
			{id: 'P005', name: 'Data Dragon', position: 'Data Engineer', category: 'Python', technologies: ['Python','Apache Spark','Kafka','Airflow','BigQuery'], experienceYears: 7, salaryUSD: 5400, englishLevel: 'Upper-Intermediate', industry: 'Analytics • AdTech', rating: 4.9, techLevel: 118, availability: '1 month notice', businessImpact: 'Data pipeline processing 100TB+ daily • Real-time analytics dashboard'},
			{id: 'N001', name: 'API Assassin', position: 'Senior Node.js Developer', category: 'Node.js', technologies: ['Node.js','Express','MongoDB','Redis','Docker'], experienceYears: 8, salaryUSD: 6200, englishLevel: 'Advanced', industry: 'Enterprise • API Services', rating: 4.9, techLevel: 138, availability: 'Available now', businessImpact: 'Microservices architecture serving 5M+ requests daily • 99.99% uptime'},
			{id: 'N002', name: 'Real-time Ruler', position: 'Node.js Full-stack Developer', category: 'Node.js', technologies: ['Node.js','Socket.io','React','PostgreSQL','AWS'], experienceYears: 6, salaryUSD: 5100, englishLevel: 'Upper-Intermediate', industry: 'Gaming • Real-time Apps', rating: 4.8, techLevel: 112, availability: '2 weeks notice', businessImpact: 'Real-time multiplayer game with 100k+ concurrent users • WebSocket optimization'},
			{id: 'N003', name: 'Crypto Commander', position: 'Blockchain Node.js Developer', category: 'Node.js', technologies: ['Node.js','Web3','Ethereum','Solidity','TypeScript'], experienceYears: 5, salaryUSD: 7200, englishLevel: 'Advanced', industry: 'Crypto • DeFi', rating: 4.9, techLevel: 145, availability: 'Available now', businessImpact: 'DeFi protocol with $500M+ TVL • Smart contract integration'},
			{id: 'J001', name: 'Enterprise Emperor', position: 'Senior Java Developer', category: 'Java', technologies: ['Java','Spring Boot','Hibernate','Kafka','Docker'], experienceYears: 10, salaryUSD: 7500, englishLevel: 'Advanced', industry: 'Enterprise • Banking', rating: 5.0, techLevel: 165, availability: '1 month notice', businessImpact: 'Banking system processing $10B+ daily • Microservices architecture'},
			{id: 'J002', name: 'Performance Pro', position: 'Java Backend Engineer', category: 'Java', technologies: ['Java','Spring','MySQL','Redis','Elasticsearch'], experienceYears: 7, salaryUSD: 6000, englishLevel: 'Upper-Intermediate', industry: 'E-commerce • High Load', rating: 4.9, techLevel: 128, availability: 'Available now', businessImpact: 'E-commerce platform handling 1M+ orders daily • Performance optimization'}
		];'''

with open('updated_developers.js', 'w') as f:
    f.write(developers_js)

print("Generated 20 developers with cool names!")
print("Hot deals criteria should now show some developers!")